# Generated by Django 4.2.1 on 2023-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('user', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phoneNumber', models.TextField()),
                ('linkedIn', models.TextField()),
                ('gitHub', models.TextField()),
                ('instagram', models.TextField()),
                ('facebook', models.TextField()),
                ('resume', models.FileField(default=None, upload_to='resumes')),
                ('resumeFileName', models.TextField()),
            ],
        ),
    ]
